#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer
#IP (lb-01). Let’s also add other subdomains to make our life easier,
#and write a Bash script that will display information about subdomains

print_domains() {
	if [ -z "$2" ]; then
		dig "www.$1" | awk '$4=="A" {print "The subdomain www is a " $4 " record and points to " $5}'
		dig "lb-01.$1" | awk '$4=="A" {print "The subdomain lb-01 is a " $4 " record and points to " $5}'
		dig "web-01.$1" | awk '$4=="A" {print "The subdomain web-01 is a " $4 " record and points to " $5}'
		dig "web-02.$1" | awk '$4=="A" {print "The subdomain web-02 is a " $4 " record and points to " $5}'
	else
		dig "$2.$1" | awk -v SUB_DOMAIN="$2" '$4=="A" {print "The subdomain " SUB_DOMAIN " is a " $4 " record and points to " $5}'
	fi
}

print_domains "$1" "$2"

