#!/usr/bin/env bash
# Setup Nginx Web Server

# Update the system & install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx HTTP
sudo ufw allow "Nginx HTTP"

# setup the web
echo 'Hello World!' > /var/www/html/index.html

# start Nginx server
sudo service nginx restart

