#!/usr/bin/env bash
#Setup Nginx Web Server
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER:$USER" /var/www
echo 'Hello World!' > /var/www/html/index-nginx.html
sudo service nginx start

