#!/usr/bin/env bash
#Configuring and Setup a Nginx Server
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx listrning on port 80
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Server Configuration
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

# Enabling the "redirect" method
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/


# Restarting Nginx Web Server
sudo nginx -t
sudo service nginx reload
