#!/usr/bin/env bash
# Configuring web-02 to be identical to web-01
# always remember to automate your work
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
server_config=\
"server {
                listen 80 default_server;
                listen [::]:80 default_server;
                root /var/www/html;
                index index.html
                server_name_;
                add_header X-Served-By \$hostname;
                location / {
                        try_files \$uri \$uri/ =404;
                }
                if (\$request_filename ~ redirect_me){
                        rewrite ^ https://www.alxafrica.com/ permanent;
                }
                error_page 404 /error_404.html;
                location = /error_404.html {
                        internal;
                }
}"
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
sudo service nginx start

