#!/usr/bin/env bash
# It's sound terrifying when you use kill to kill a pid :)
n=0
trap "echo I hate the kill command & rm /var/run/myscript.pid & exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'rm /var/run/myscript.pid & exit' SIGQUIT

echo $$ > /var/run/holbertonscript.pid
while [ $n == 0 ]
do
    echo "To infinity and beyond"
    sleep 2
done
