#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username _ userid groupid _ _ homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo -n "User ID's place is protected by the passcode. Please enter the passcode: "
    read -r password
    echo "The passcode you entered is $password. More info about the user $userid here: USER ID INFO"
    echo
done < "/etc/passwd"
