#!/usr/bin/env bash
# Making clock

hour=0
minute=1
count=0

while [ $count -lt 70 ]
do
    if [ "$minute" -eq 1 ]
    then
        echo "Hour: $hour"
    fi
    echo $minute

    ((count++))
    ((minute++))

    if [ "$minute" -gt 59 ]
    then
        ((hour++))
        minute=1
    fi
done
