#!/usr/bin/env bash
# Writing a Bash script that configures an Ubuntu server

cp /etch/hosts ~/new_hosts.new
echo "127.0.0.1 localhost" > ~/new_hosts.new
echo "8.8.8.8 facebook.com" >> ~/new_hosts.new
cp -f ~/new_hosts.new /etc/hosts
