#!/usr/bin/env bash
# Writing a Bash script that configures an Ubuntu server

cp /etch/hosts ~/new_hosts.new
echo "127.0.0.1 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
